language: c
env:
  - MCCFLAGS="-inline 0"
  - MCCFLAGS="-inline 5"
  - MCCFLAGS="-inline 10"
  - MCCFLAGS="-inline 0 -finv"
  - MCCFLAGS="-inline 5 -finv"
  - MCCFLAGS="-inline 10 -finv"
  - MCCFLAGS="-inline 0 -fsqrt"
  - MCCFLAGS="-inline 5 -fsqrt"
  - MCCFLAGS="-inline 10 -fsqrt"
  - MCCFLAGS="-inline 0 -finv -fsqrt"
  - MCCFLAGS="-inline 5 -finv -fsqrt"
  - MCCFLAGS="-inline 10 -finv -fsqrt"
before_install:
  - git submodule update --init --recursive
script:
  - sudo apt-get update -qq
  - sudo apt-get install ocaml omake
  - make MCCFLAGS="${MCCFLAGS}"
  - make MCCFLAGS="${MCCFLAGS}" raytrace >/dev/null 2>/dev/null
  - time make -C ray-run/ contest.run

